FROM golang:1.22 AS build-stage

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . ./

RUN CGO_ENABLED=0 GOOS=linux go build -o /go-market-warehouse-api ./cmd/main.go

FROM gcr.io/distroless/base-debian11 as build-release-stage

WORKDIR /

COPY --from=build-stage /go-market-warehouse-api /go-market-warehouse-api

EXPOSE 8000

USER nonroot:nonroot

ENTRYPOINT [ "/go-market-warehouse-api" ]

